// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: analysis/v1/analysis.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyProjectPathReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *VerifyProjectPathReq) Reset() {
	*x = VerifyProjectPathReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyProjectPathReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyProjectPathReq) ProtoMessage() {}

func (x *VerifyProjectPathReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyProjectPathReq.ProtoReflect.Descriptor instead.
func (*VerifyProjectPathReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyProjectPathReq) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type VerifyProjectPathReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verified bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (x *VerifyProjectPathReply) Reset() {
	*x = VerifyProjectPathReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyProjectPathReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyProjectPathReply) ProtoMessage() {}

func (x *VerifyProjectPathReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyProjectPathReply.ProtoReflect.Descriptor instead.
func (*VerifyProjectPathReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyProjectPathReply) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type GetGidsByFunctionNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionName string `protobuf:"bytes,1,opt,name=functionName,proto3" json:"functionName,omitempty"`
}

func (x *GetGidsByFunctionNameReq) Reset() {
	*x = GetGidsByFunctionNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGidsByFunctionNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGidsByFunctionNameReq) ProtoMessage() {}

func (x *GetGidsByFunctionNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGidsByFunctionNameReq.ProtoReflect.Descriptor instead.
func (*GetGidsByFunctionNameReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *GetGidsByFunctionNameReq) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

type GetGidsByFunctionNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body  []*GetGidsByFunctionNameReply_Body `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	Total int32                              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总的 GID 数量
}

func (x *GetGidsByFunctionNameReply) Reset() {
	*x = GetGidsByFunctionNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGidsByFunctionNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGidsByFunctionNameReply) ProtoMessage() {}

func (x *GetGidsByFunctionNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGidsByFunctionNameReply.ProtoReflect.Descriptor instead.
func (*GetGidsByFunctionNameReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *GetGidsByFunctionNameReply) GetBody() []*GetGidsByFunctionNameReply_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetGidsByFunctionNameReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAllFunctionNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllFunctionNameReq) Reset() {
	*x = GetAllFunctionNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFunctionNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFunctionNameReq) ProtoMessage() {}

func (x *GetAllFunctionNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFunctionNameReq.ProtoReflect.Descriptor instead.
func (*GetAllFunctionNameReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{4}
}

type GetAllFunctionNameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionNames []string `protobuf:"bytes,1,rep,name=functionNames,proto3" json:"functionNames,omitempty"`
}

func (x *GetAllFunctionNameReply) Reset() {
	*x = GetAllFunctionNameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFunctionNameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFunctionNameReply) ProtoMessage() {}

func (x *GetAllFunctionNameReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFunctionNameReply.ProtoReflect.Descriptor instead.
func (*GetAllFunctionNameReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllFunctionNameReply) GetFunctionNames() []string {
	if x != nil {
		return x.FunctionNames
	}
	return nil
}

type GenerateImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *GenerateImageReq) Reset() {
	*x = GenerateImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageReq) ProtoMessage() {}

func (x *GenerateImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageReq.ProtoReflect.Descriptor instead.
func (*GenerateImageReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateImageReq) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type GenerateImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *GenerateImageReply) Reset() {
	*x = GenerateImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateImageReply) ProtoMessage() {}

func (x *GenerateImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateImageReply.ProtoReflect.Descriptor instead.
func (*GenerateImageReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateImageReply) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

// The request message containing the user's name.
type AnalysisRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *AnalysisRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type AnalysisReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AnalysisReply) Reset() {
	*x = AnalysisReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisReply) ProtoMessage() {}

func (x *AnalysisReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisReply.ProtoReflect.Descriptor instead.
func (*AnalysisReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *AnalysisReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AnalysisByGIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *AnalysisByGIDRequest) Reset() {
	*x = AnalysisByGIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisByGIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisByGIDRequest) ProtoMessage() {}

func (x *AnalysisByGIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisByGIDRequest.ProtoReflect.Descriptor instead.
func (*AnalysisByGIDRequest) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *AnalysisByGIDRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type TraceParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos   int32  `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Param string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *TraceParams) Reset() {
	*x = TraceParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TraceParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceParams) ProtoMessage() {}

func (x *TraceParams) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceParams.ProtoReflect.Descriptor instead.
func (*TraceParams) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{11}
}

func (x *TraceParams) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *TraceParams) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type AnalysisByGIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceData []*AnalysisByGIDReply_TraceData `protobuf:"bytes,1,rep,name=trace_data,json=traceData,proto3" json:"trace_data,omitempty"`
}

func (x *AnalysisByGIDReply) Reset() {
	*x = AnalysisByGIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisByGIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisByGIDReply) ProtoMessage() {}

func (x *AnalysisByGIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisByGIDReply.ProtoReflect.Descriptor instead.
func (*AnalysisByGIDReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{12}
}

func (x *AnalysisByGIDReply) GetTraceData() []*AnalysisByGIDReply_TraceData {
	if x != nil {
		return x.TraceData
	}
	return nil
}

type GetAllGIDsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`   // 当前页
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // 每页条目数
}

func (x *GetAllGIDsReq) Reset() {
	*x = GetAllGIDsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllGIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGIDsReq) ProtoMessage() {}

func (x *GetAllGIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGIDsReq.ProtoReflect.Descriptor instead.
func (*GetAllGIDsReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllGIDsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllGIDsReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllGIDsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body  []*GetAllGIDsReply_Body `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	Total int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总的 GID 数量
}

func (x *GetAllGIDsReply) Reset() {
	*x = GetAllGIDsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllGIDsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGIDsReply) ProtoMessage() {}

func (x *GetAllGIDsReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGIDsReply.ProtoReflect.Descriptor instead.
func (*GetAllGIDsReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{14}
}

func (x *GetAllGIDsReply) GetBody() []*GetAllGIDsReply_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *GetAllGIDsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetParamsByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetParamsByIDReq) Reset() {
	*x = GetParamsByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamsByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamsByIDReq) ProtoMessage() {}

func (x *GetParamsByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamsByIDReq.ProtoReflect.Descriptor instead.
func (*GetParamsByIDReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{15}
}

func (x *GetParamsByIDReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetParamsByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Params []*TraceParams `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
}

func (x *GetParamsByIDReply) Reset() {
	*x = GetParamsByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetParamsByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamsByIDReply) ProtoMessage() {}

func (x *GetParamsByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamsByIDReply.ProtoReflect.Descriptor instead.
func (*GetParamsByIDReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{16}
}

func (x *GetParamsByIDReply) GetParams() []*TraceParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type CheckDatabaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckDatabaseRequest) Reset() {
	*x = CheckDatabaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDatabaseRequest) ProtoMessage() {}

func (x *CheckDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CheckDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{17}
}

type CheckDatabaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *CheckDatabaseResponse) Reset() {
	*x = CheckDatabaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDatabaseResponse) ProtoMessage() {}

func (x *CheckDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CheckDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{18}
}

func (x *CheckDatabaseResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GraphNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CallCount int32  `protobuf:"varint,3,opt,name=call_count,json=callCount,proto3" json:"call_count,omitempty"`
}

func (x *GraphNode) Reset() {
	*x = GraphNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNode) ProtoMessage() {}

func (x *GraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNode.ProtoReflect.Descriptor instead.
func (*GraphNode) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{19}
}

func (x *GraphNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GraphNode) GetCallCount() int32 {
	if x != nil {
		return x.CallCount
	}
	return 0
}

type GraphEdge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Label  string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{20}
}

func (x *GraphEdge) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GraphEdge) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GraphEdge) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetTraceGraphReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid string `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
}

func (x *GetTraceGraphReq) Reset() {
	*x = GetTraceGraphReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTraceGraphReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceGraphReq) ProtoMessage() {}

func (x *GetTraceGraphReq) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceGraphReq.ProtoReflect.Descriptor instead.
func (*GetTraceGraphReq) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{21}
}

func (x *GetTraceGraphReq) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type GetTraceGraphReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*GraphNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges []*GraphEdge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
}

func (x *GetTraceGraphReply) Reset() {
	*x = GetTraceGraphReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTraceGraphReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceGraphReply) ProtoMessage() {}

func (x *GetTraceGraphReply) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceGraphReply.ProtoReflect.Descriptor instead.
func (*GetTraceGraphReply) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{22}
}

func (x *GetTraceGraphReply) GetNodes() []*GraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetTraceGraphReply) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GetGidsByFunctionNameReply_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid         uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	InitialFunc string `protobuf:"bytes,2,opt,name=initialFunc,proto3" json:"initialFunc,omitempty"`
}

func (x *GetGidsByFunctionNameReply_Body) Reset() {
	*x = GetGidsByFunctionNameReply_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGidsByFunctionNameReply_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGidsByFunctionNameReply_Body) ProtoMessage() {}

func (x *GetGidsByFunctionNameReply_Body) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGidsByFunctionNameReply_Body.ProtoReflect.Descriptor instead.
func (*GetGidsByFunctionNameReply_Body) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetGidsByFunctionNameReply_Body) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GetGidsByFunctionNameReply_Body) GetInitialFunc() string {
	if x != nil {
		return x.InitialFunc
	}
	return ""
}

type AnalysisByGIDReply_TraceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Gid        int32          `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	Indent     int32          `protobuf:"varint,4,opt,name=indent,proto3" json:"indent,omitempty"`
	Params     []*TraceParams `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty"`
	ParamCount int32          `protobuf:"varint,6,opt,name=paramCount,proto3" json:"paramCount,omitempty"`
	TimeCost   string         `protobuf:"bytes,7,opt,name=timeCost,proto3" json:"timeCost,omitempty"`
}

func (x *AnalysisByGIDReply_TraceData) Reset() {
	*x = AnalysisByGIDReply_TraceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnalysisByGIDReply_TraceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisByGIDReply_TraceData) ProtoMessage() {}

func (x *AnalysisByGIDReply_TraceData) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisByGIDReply_TraceData.ProtoReflect.Descriptor instead.
func (*AnalysisByGIDReply_TraceData) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{12, 0}
}

func (x *AnalysisByGIDReply_TraceData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnalysisByGIDReply_TraceData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AnalysisByGIDReply_TraceData) GetGid() int32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *AnalysisByGIDReply_TraceData) GetIndent() int32 {
	if x != nil {
		return x.Indent
	}
	return 0
}

func (x *AnalysisByGIDReply_TraceData) GetParams() []*TraceParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *AnalysisByGIDReply_TraceData) GetParamCount() int32 {
	if x != nil {
		return x.ParamCount
	}
	return 0
}

func (x *AnalysisByGIDReply_TraceData) GetTimeCost() string {
	if x != nil {
		return x.TimeCost
	}
	return ""
}

type GetAllGIDsReply_Body struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gid         uint64 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	InitialFunc string `protobuf:"bytes,2,opt,name=initialFunc,proto3" json:"initialFunc,omitempty"`
}

func (x *GetAllGIDsReply_Body) Reset() {
	*x = GetAllGIDsReply_Body{}
	if protoimpl.UnsafeEnabled {
		mi := &file_analysis_v1_analysis_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllGIDsReply_Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllGIDsReply_Body) ProtoMessage() {}

func (x *GetAllGIDsReply_Body) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllGIDsReply_Body.ProtoReflect.Descriptor instead.
func (*GetAllGIDsReply_Body) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{14, 0}
}

func (x *GetAllGIDsReply_Body) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *GetAllGIDsReply_Body) GetInitialFunc() string {
	if x != nil {
		return x.InitialFunc
	}
	return ""
}

var File_analysis_v1_analysis_proto protoreflect.FileDescriptor

var file_analysis_v1_analysis_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x34, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x3e, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x47, 0x69, 0x64, 0x73, 0x42, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x47, 0x69, 0x64, 0x73, 0x42, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x64, 0x73, 0x42, 0x79, 0x46, 0x75,
	0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x1a, 0x3a, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x22, 0x17, 0x0a, 0x15,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x24, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x12,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x6e, 0x61, 0x6c,
	0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x29, 0x0a, 0x0d, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x14, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x67, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0xa8, 0x02, 0x0a, 0x12,
	0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47, 0x49, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x48, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47,
	0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x74, 0x72, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0xc7, 0x01, 0x0a,
	0x09, 0x54, 0x72, 0x61, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x67, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x67, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x6e, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69,
	0x6d, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x47, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x9a, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x49, 0x44, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x1a, 0x3a, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x22, 0x22,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x2f, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x22, 0x4e, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x51, 0x0a, 0x09, 0x47, 0x72, 0x61, 0x70, 0x68, 0x45, 0x64, 0x67, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x32, 0xf6,
	0x08, 0x0a, 0x08, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x61, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12, 0x1c, 0x2e, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x71,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47,
	0x49, 0x44, 0x12, 0x21, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x42, 0x79, 0x47, 0x49,
	0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x67, 0x69, 0x64,
	0x7d, 0x12, 0x59, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x47, 0x49, 0x44, 0x73, 0x12,
	0x1a, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x47, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x47, 0x49, 0x44, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0b, 0x12, 0x09, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x69, 0x64, 0x73, 0x12, 0x69, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1d, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x12, 0x12, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x72, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b,
	0x12, 0x19, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x67,
	0x69, 0x64, 0x7d, 0x2f, 0x6d, 0x65, 0x72, 0x6d, 0x61, 0x69, 0x64, 0x12, 0x76, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x86, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x69, 0x64, 0x73, 0x42,
	0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x2e,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x69, 0x64, 0x73, 0x42, 0x79, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x69, 0x64, 0x73, 0x42, 0x79, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1d, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x17, 0x3a, 0x01, 0x2a, 0x22, 0x12, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x69, 0x64, 0x73, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x78, 0x0a, 0x11,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x21, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x15, 0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x12, 0x6d, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x61,
	0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x2f, 0x64, 0x62, 0x12, 0x70, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1d, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x12, 0x17,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x73, 0x2f, 0x7b, 0x67, 0x69, 0x64,
	0x7d, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x2f, 0x67, 0x6f,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x73, 0x69, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_analysis_v1_analysis_proto_rawDescOnce sync.Once
	file_analysis_v1_analysis_proto_rawDescData = file_analysis_v1_analysis_proto_rawDesc
)

func file_analysis_v1_analysis_proto_rawDescGZIP() []byte {
	file_analysis_v1_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(file_analysis_v1_analysis_proto_rawDescData)
	})
	return file_analysis_v1_analysis_proto_rawDescData
}

var file_analysis_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_analysis_v1_analysis_proto_goTypes = []interface{}{
	(*VerifyProjectPathReq)(nil),            // 0: analysis.v1.VerifyProjectPathReq
	(*VerifyProjectPathReply)(nil),          // 1: analysis.v1.VerifyProjectPathReply
	(*GetGidsByFunctionNameReq)(nil),        // 2: analysis.v1.GetGidsByFunctionNameReq
	(*GetGidsByFunctionNameReply)(nil),      // 3: analysis.v1.GetGidsByFunctionNameReply
	(*GetAllFunctionNameReq)(nil),           // 4: analysis.v1.GetAllFunctionNameReq
	(*GetAllFunctionNameReply)(nil),         // 5: analysis.v1.GetAllFunctionNameReply
	(*GenerateImageReq)(nil),                // 6: analysis.v1.GenerateImageReq
	(*GenerateImageReply)(nil),              // 7: analysis.v1.GenerateImageReply
	(*AnalysisRequest)(nil),                 // 8: analysis.v1.AnalysisRequest
	(*AnalysisReply)(nil),                   // 9: analysis.v1.AnalysisReply
	(*AnalysisByGIDRequest)(nil),            // 10: analysis.v1.AnalysisByGIDRequest
	(*TraceParams)(nil),                     // 11: analysis.v1.TraceParams
	(*AnalysisByGIDReply)(nil),              // 12: analysis.v1.AnalysisByGIDReply
	(*GetAllGIDsReq)(nil),                   // 13: analysis.v1.GetAllGIDsReq
	(*GetAllGIDsReply)(nil),                 // 14: analysis.v1.GetAllGIDsReply
	(*GetParamsByIDReq)(nil),                // 15: analysis.v1.GetParamsByIDReq
	(*GetParamsByIDReply)(nil),              // 16: analysis.v1.GetParamsByIDReply
	(*CheckDatabaseRequest)(nil),            // 17: analysis.v1.CheckDatabaseRequest
	(*CheckDatabaseResponse)(nil),           // 18: analysis.v1.CheckDatabaseResponse
	(*GraphNode)(nil),                       // 19: analysis.v1.GraphNode
	(*GraphEdge)(nil),                       // 20: analysis.v1.GraphEdge
	(*GetTraceGraphReq)(nil),                // 21: analysis.v1.GetTraceGraphReq
	(*GetTraceGraphReply)(nil),              // 22: analysis.v1.GetTraceGraphReply
	(*GetGidsByFunctionNameReply_Body)(nil), // 23: analysis.v1.GetGidsByFunctionNameReply.Body
	(*AnalysisByGIDReply_TraceData)(nil),    // 24: analysis.v1.AnalysisByGIDReply.TraceData
	(*GetAllGIDsReply_Body)(nil),            // 25: analysis.v1.GetAllGIDsReply.Body
}
var file_analysis_v1_analysis_proto_depIdxs = []int32{
	23, // 0: analysis.v1.GetGidsByFunctionNameReply.body:type_name -> analysis.v1.GetGidsByFunctionNameReply.Body
	24, // 1: analysis.v1.AnalysisByGIDReply.trace_data:type_name -> analysis.v1.AnalysisByGIDReply.TraceData
	25, // 2: analysis.v1.GetAllGIDsReply.body:type_name -> analysis.v1.GetAllGIDsReply.Body
	11, // 3: analysis.v1.GetParamsByIDReply.params:type_name -> analysis.v1.TraceParams
	19, // 4: analysis.v1.GetTraceGraphReply.nodes:type_name -> analysis.v1.GraphNode
	20, // 5: analysis.v1.GetTraceGraphReply.edges:type_name -> analysis.v1.GraphEdge
	11, // 6: analysis.v1.AnalysisByGIDReply.TraceData.params:type_name -> analysis.v1.TraceParams
	8,  // 7: analysis.v1.Analysis.GetAnalysis:input_type -> analysis.v1.AnalysisRequest
	10, // 8: analysis.v1.Analysis.GetAnalysisByGID:input_type -> analysis.v1.AnalysisByGIDRequest
	13, // 9: analysis.v1.Analysis.GetAllGIDs:input_type -> analysis.v1.GetAllGIDsReq
	15, // 10: analysis.v1.Analysis.GetParamsByID:input_type -> analysis.v1.GetParamsByIDReq
	6,  // 11: analysis.v1.Analysis.GenerateImage:input_type -> analysis.v1.GenerateImageReq
	4,  // 12: analysis.v1.Analysis.GetAllFunctionName:input_type -> analysis.v1.GetAllFunctionNameReq
	2,  // 13: analysis.v1.Analysis.GetGidsByFunctionName:input_type -> analysis.v1.GetGidsByFunctionNameReq
	0,  // 14: analysis.v1.Analysis.VerifyProjectPath:input_type -> analysis.v1.VerifyProjectPathReq
	17, // 15: analysis.v1.Analysis.CheckDatabase:input_type -> analysis.v1.CheckDatabaseRequest
	21, // 16: analysis.v1.Analysis.GetTraceGraph:input_type -> analysis.v1.GetTraceGraphReq
	9,  // 17: analysis.v1.Analysis.GetAnalysis:output_type -> analysis.v1.AnalysisReply
	12, // 18: analysis.v1.Analysis.GetAnalysisByGID:output_type -> analysis.v1.AnalysisByGIDReply
	14, // 19: analysis.v1.Analysis.GetAllGIDs:output_type -> analysis.v1.GetAllGIDsReply
	16, // 20: analysis.v1.Analysis.GetParamsByID:output_type -> analysis.v1.GetParamsByIDReply
	7,  // 21: analysis.v1.Analysis.GenerateImage:output_type -> analysis.v1.GenerateImageReply
	5,  // 22: analysis.v1.Analysis.GetAllFunctionName:output_type -> analysis.v1.GetAllFunctionNameReply
	3,  // 23: analysis.v1.Analysis.GetGidsByFunctionName:output_type -> analysis.v1.GetGidsByFunctionNameReply
	1,  // 24: analysis.v1.Analysis.VerifyProjectPath:output_type -> analysis.v1.VerifyProjectPathReply
	18, // 25: analysis.v1.Analysis.CheckDatabase:output_type -> analysis.v1.CheckDatabaseResponse
	22, // 26: analysis.v1.Analysis.GetTraceGraph:output_type -> analysis.v1.GetTraceGraphReply
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_analysis_v1_analysis_proto_init() }
func file_analysis_v1_analysis_proto_init() {
	if File_analysis_v1_analysis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_analysis_v1_analysis_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyProjectPathReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyProjectPathReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGidsByFunctionNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGidsByFunctionNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFunctionNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFunctionNameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisByGIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TraceParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisByGIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllGIDsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllGIDsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamsByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetParamsByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDatabaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckDatabaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphEdge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTraceGraphReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTraceGraphReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGidsByFunctionNameReply_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnalysisByGIDReply_TraceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_analysis_v1_analysis_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllGIDsReply_Body); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_analysis_v1_analysis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_v1_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_v1_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_v1_analysis_proto_msgTypes,
	}.Build()
	File_analysis_v1_analysis_proto = out.File
	file_analysis_v1_analysis_proto_rawDesc = nil
	file_analysis_v1_analysis_proto_goTypes = nil
	file_analysis_v1_analysis_proto_depIdxs = nil
}
