// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/toheart/goanalysis/internal/biz/analysis"
	"github.com/toheart/goanalysis/internal/conf"
	"github.com/toheart/goanalysis/internal/data"
	"github.com/toheart/goanalysis/internal/server"
	"github.com/toheart/goanalysis/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, biz *conf.Biz, logger log.Logger) (*kratos.App, func(), error) {
	dataData := data.NewData(logger)
	analysisBiz := analysis.NewAnalysisBiz(biz, dataData, logger)
	analysisService := service.NewAnalysisService(analysisBiz)
	grpcServer := server.NewGRPCServer(confServer, analysisService, logger)
	httpServer := server.NewHTTPServer(confServer, analysisService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
